### ISSUE TITLE
Trying to convert a png_xbox (format 26) file to png with superfreq is failing

### ISSUE THREAD

**Issue by qfoxb** [PikminGuts92/Mackiloha#21]
I'm using `superfreq tex2png file.png_xbox file.png --platform x360 --miloVersion 26` to convert a texture from RB3 to png, and i'm getting 
```
Unhandled exception. System.NotSupportedException: HMXBitmapReader: Expected 0x01 at offset 0
   at Mackiloha.IO.Serializers.HMXBitmapSerializer.ReadFromStream(AwesomeReader ar, ISerializable data)
   at Mackiloha.IO.MiloSerializer.ReadFromStream(Stream stream, ISerializable data)
   at Mackiloha.IO.MiloSerializer.ReadFromStream[T](Stream stream)
   at Mackiloha.IO.MiloSerializer.ReadFromFile[T](String path)
   at SuperFreqCLI.Options.TextureToPngOptions.Parse(TextureToPngOptions op)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at SuperFreqCLI.Program.Main(String[] args) 
```
every time i've tried to run it

This is on a machine running Ubuntu 23.04

**Comment by PikminGuts92** [comment]
File could be corrupt. Which texture?

**Comment by qfoxb** [comment]
all of them appear to do it - files from rb3 disc (ui_picture_keep.png_xbox) and files converted to texture with superfreq [test file](https://files.catbox.moe/cidrub.png_xbox)

**Comment by PikminGuts92** [comment]
Is this with using the latest version from here? How were the files extracted? https://github.com/PikminGuts92/Mackiloha/releases/tag/v1.3.1

**Comment by qfoxb** [comment]
File was corrupted. :clueless:
