### ISSUE TITLE
Milo2Gltf Unhandled exception. System.NotSupportedException: ViewSerializer: Magic 0x0C does not correspond to serializer version 0x19 (Expected 0x0E)

### ISSUE THREAD

**Issue by DarkFireSF** [PikminGuts92/Mackiloha#6]
When I run superfreq milo2gltf metal_singer.milo_xbox gh2_metal_singer_x_360 --platform=x360 --preset=gh2_x360 I get this error:
```
Unhandled exception. System.NotSupportedException: ViewSerializer: Magic 0x0C does not correspond to serializer version 0x19 (Expected 0x0E)
   at Mackiloha.IO.AbstractSerializer.ReadMagic(AwesomeReader ar, ISerializable data)
   at Mackiloha.IO.Serializers.ViewSerializer.ReadFromStream(AwesomeReader ar, ISerializable data)
   at Mackiloha.IO.MiloSerializer.ReadFromStream(Stream stream, ISerializable data)
   at Mackiloha.IO.MiloSerializer.ReadFromStream[T](Stream stream)
   at Mackiloha.App.Extensions.SerializerExtensions.ReadFromMiloObjectBytes[T](MiloSerializer serializer, MiloObjectBytes entry)
   at Mackiloha.App.Extensions.MiloExtensions.<>c__DisplayClass3_0.<ExportToGLTF>b__6(MiloObject y)
   at System.Linq.Enumerable.WhereSelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Mackiloha.App.Extensions.MiloExtensions.ExportToGLTF(MiloObjectDir milo, String path, AppState appState)
   at SuperFreqCLI.Options.Milo2GLTFOptions.Parse(Milo2GLTFOptions op)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at SuperFreqCLI.Program.Main(String[] args)
```
how do I fix this?

**Comment by PikminGuts92** [comment]
I'm not sure. GLTF export is barely functional as it is. If someone figures it out then I can put in a fix. But this isn't a high priority for me.

**Comment by PikminGuts92** [comment]
Gltf support has been removed #15
